function(silence target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W0 /WX-)
  else()
    target_compile_options(${target} PRIVATE -w -Wno-error)
  endif()
  set_target_properties(${target} PROPERTIES CXX_CLANG_TIDY "")
  set_target_properties(${target} PROPERTIES CXX_CPPCHECK "")
  set_target_properties(${target} PROPERTIES CXX_CPPLINT "")
endfunction()
